[project]
name = "111"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "9932155", email = "2014023261@qq.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
111 = "111:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
